-- Supabase 는 anon/public 키로 PostgREST 를 열어놓는다 — RLS 를 켜지 않으면
-- 브라우저에서 아무 테이블이나 읽을 수 있다. 우리는 PostgREST 를 쓰지 않고
-- NestJS 로만 붙지만, 방어선을 하나 더 두는 것이 정책 (BACKEND_GUIDE).
-- 정책은 만들지 않는다 — service_role 만 접근하고, 정책 없는 RLS 는 전부 거절이다.

ALTER TABLE "competitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "seasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "competition_seasons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "competition_rounds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "venues" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "competition_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "external_ids" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "players" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "squad_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "coaches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "coach_tenures" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "matches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "knockout_ties" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bracket_slots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "match_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "match_lineups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lineup_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "team_match_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "player_match_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "standings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "player_season_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "team_season_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "top_rankings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "injuries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "backfill_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ingestion_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_quota_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "localized_names" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
